services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - mysql_root_pw
      - mysql_pw

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception_network
    depends_on:
      - mariadb
    secrets:
      - mysql_pw
      - wp_admin_pw
      - wp_user_pw
  
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - wordpress_files:/var/www/html:ro  # Read-only access to WordPress files
    ports: #Left = Host machine (VM in this project) : Right = Container
      - "443:443"
      - "80:80"   # HTTP connection which should be rejected
    networks:
      - inception_network

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/gita/data/mariadb
      o: bind

  wordpress_files:
    name: wordpress_files
    driver: local
    driver_opts:
      type: none
      device: /home/gita/data/wordpress
      o: bind

networks:
  inception_network:
    name: inception_network
    driver: bridge

secrets:
  mysql_root_pw:
    file: ../secrets/mysql_root_pw.txt
  mysql_pw:
    file: ../secrets/mysql_pw.txt
  wp_admin_pw:
    file: ../secrets/wp_admin_pw.txt
  wp_user_pw:
    file: ../secrets/wp_user_pw.txt